version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    expose:
      - 9090
    links:
      - ktranslate:ktranslate
      - node-exporter:node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
      - 9100

  ktranslate:
     image: kentik/ktranslate:v2
     container_name: ktranslate
     restart: unless-stopped
     expose:
       - 8084
       - 8083
       - 8082
     volumes:
       - ./kentik:/kentik
     ports:
       - 8082:8082
       - 8083:8083
     dns:
       - 1.1.1.1
     command:
       - '--prom_listen=:8084'
       - '--sinks=prometheus'
       - '--format=prometheus'
       - '--rollups=s_percentile100,in_bytes,protocol'
       - '--rollups=s_percentile100,out_bytes,protocol'
       - '--rollups=s_percentile100,in_pkts,src_geo_region,dst_geo_region'
       - '--rollups=s_percentile100,out_pkts,src_geo_region,dst_geo_region'
       - '--rollups=s_percentile100,out_pkts+in_pkts,l4_dst_port,l4_src_port'
       - '--rollups=percentile90,custom_int.APPL_LATENCY_MS,custom_str.src_host,custom_str.dst_host'
       - '--dns=1.1.1.1:53'
       - '--geo=/kentik/country.csv'
       - '--asn4=/kentik/ipv4-asn-ip.csv'
       - '--asn6=/kentik/ipv6-asn-ip.csv'

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboard.json:/usr/share/grafana/dashboards/dashboard.json
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=therealdeal
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SMTP_ENABLED=false

  kprobe:
    image: kentik/kprobe:latest
    container_name: kprobe
    restart: unless-stopped
    network_mode: host
    command:
      - '/usr/bin/kprobe'
      - '--interface'
      - ${KENTIK_INTERFACE}
      - '--email'
      - 'not@useful.com'
      - '--token'
      - 'abc123'
      - '--device-id'
      - '26494'
      - '--flow-url'
      - 'http://127.0.0.1:8082/chf'
      - '--api-url'
      - 'http://127.0.0.1:3030'
    depends_on:
      - ktranslate

  auth-mock:
    image: keeb/kentik-auth-mock:latest
    container_name: auth-mock
    restart: unless-stopped
    ports:
      - 3030:3030
    expose:
      - 3030
