version: "3.9"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - ktranslate:ktranslate
      - node-exporter:node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
      - 9100

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboard.json:/usr/share/grafana/dashboards/dashboard.json
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=therealdeal
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SMTP_ENABLED=false
    depends_on:
      - prometheus

  ktranslate:
     image: kentik/ktranslate:v2
     container_name: ktranslate
     restart: unless-stopped
     expose:
       - 8084
       - 8083
       - 8082
     volumes:
       - ./kentik:/kentik
     ports:
       - 8082:8082
       - 8083:8083
     command:
       - '--prom_listen=:8084'
       - '--sinks=prometheus'
       - '--format=prometheus'
       - '--api_devices=/etc/devices.json'
       - '--dns=1.1.1.1:53'
       - '--geo=/kentik/country.csv'
       - '--asn4=/kentik/ipv4-asn-ip.csv'
       - '--asn6=/kentik/ipv6-asn-ip.csv'

  agg:
    container_name: kappa-agg
    image: kappa:latest
    restart: unless-stopped
    command: ./kappa agg -v 127.0.0.1:4000
    environment:
      KENTIK_EMAIL:  pye@cloudhelix.com
      KENTIK_TOKEN:  XXX
      KENTIK_DEVICE: 100
      KENTIK_REGION: localhost:8082
    network_mode: host
    depends_on:
      - ktranslate

  agent:
    container_name: kappa-agent
    image: kappa:latest
    command: ./kappa agent -c ".*" -v 127.0.0.1:4000
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/sys/kernel/debug:/sys/kernel/debug"
    ulimits:
      memlock: 1024000
    depends_on:
      - agg
